### ISSUE TITLE
Couverture/Intérieur

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#1]
J'ai passé l'option 'cover' à la classe gzt, la couverture a bien été générée et avec une tranche. En revanche je ne vois pas bien comment faire pour avoir maintenant l'intérieur sans la couveture. Je dois fournir d'un côté un pdf de la couverture et de l'autre un pdf sans la couverture. Serait il possible que l'option 'cover' génère les deux fichier ?

**Comment by clairesmf** [comment]
J'ai appliqué l'option 'forprinter' à la classe. Cela a bien compilé mais cela a généré un fascicule complet avec la couverture. Je ne vois donc pas bien quelle est la différence par rapport à une compilation standard.

**Comment by clairesmf** [comment]
L'option "cover" fabrique bien la couverture mais uniquement la 1 et la 2 de couv. Il faudrait que "cover" rajoute la 3 et la 4 de couv. blanche pour l'instant. D'ailleurs ou en sont les minis instructions aux auteurs devant être sur la 3 de couv. ? Il faudrait aussi prévoir de pouvoir mettre une publicité sur la 4 de couv. sous forme d'un fichier à insérer.

L'option "forprinter" fabrique le fascicule entier avec la couverture alors que l'imprimeur souhaite un intérieur sans la couverture.

**Comment by dbitouze** [comment]
Quelle mise en page pour les 3e et 4e de couverture :
- la 3e doit-elle être similaire à la 2e de couverture : présence du « logo », contenu dans un cadre sur fond bleu, etc. ?
- en absence de publicité, la 4e de couverture doit-elle être complètement blanche ? En présence de publicité, doit-elle contenir des choses en plus et, dans l'affirmative, quoi ?

Qui se charge des mini-instructions aux auteurs ? Que doivent-elles contenir ?

**Comment by clairesmf** [comment]
Le 17 avr. 2015 à 13:01, Denis Bitouzé notifications@github.com a écrit :

> Quelle mise en page pour les 3e et 4e de couverture :
> 
> la 3e doit-elle être similaire à la 2e de couverture : présence du « logo », contenu dans un cadre sur fond bleu, etc. ?

Je dirais qu'elle doit être identique à la 2 de couverture : cadre sur fond bleu contenant les minis instructions, même police et taille de caractère mais sans le logo.

> en absence de publicité, la 4e de couverture doit-elle être complètement blanche ?

Oui

> En présence de publicité, doit-elle contenir des choses en plus et, dans l'affirmative, quoi ?

Non rien de plus.

> Qui se charge des mini instructions aux auteurs ? Que doivent-elles contenir ?

Boris ou toi me semble t'il. Elles doivent contenir quelques recommandations et l'adresse url ou trouver les instructions concernant l'utilisation de la classe. Si ce n'est pas prêt pour le numéro d'avril, ce n'est pas super grave.

En revanche il faut prévoir deux pages blanches pour le fichier de couverture généré pour l'imprimeur en l'état actuel des chose.

Claire

**Comment by dbitouze** [comment]
> > la 3e doit-elle être similaire à la 2e de couverture : présence du
> > « logo », contenu dans un cadre sur fond bleu, etc. ?
> 
> Je dirais qu'elle doit être identique à la 2 de couverture : cadre sur
> fond bleu contenant les minis instructions, même police et taille de
> caractère mais sans le logo.

Mais avec le bandeau en bas de page comme en 2e de couverture et le filet horizontal en haut de page ?

> > en absence de publicité, la 4e de couverture doit-elle être
> > complètement blanche ?
> 
> Oui

Sans bandeau en bas de page donc ?

> > En présence de publicité, doit-elle contenir des choses en plus et,
> > dans l'affirmative, quoi ?
> 
> Non rien de plus.

OK.

> > Qui se charge des mini instructions aux auteurs ? Que doivent-elles
> > contenir ?
> 
> Boris ou toi me semble t'il. Elles doivent contenir quelques
> recommandations

Recommandations LaTeX ?

> et l'adresse url ou trouver les instructions concernant l'utilisation
> de la classe.

OK. Il est trop tard pour intégrer la classe à la TeX Live 2014 mais je
compte la publier bientôt, en tous cas assez tôt (au plus tard le 15
mai) pour qu'elle soit fournie avec la TeX Live 2015.

Il me semble qu'il devrait aussi y avoir des instructions concernant la
procédure de soumission d'un manuscrit et, pour cela, je vous laisse la
main.

> Si ce n'est pas prêt pour le numéro d'avril, ce n'est pas super grave.

OK.

> En revanche il faut prévoir deux pages blanches pour le fichier de
> couverture généré pour l'imprimeur en l'état actuel des chose.

OK.

**Comment by clairesmf** [comment]
Le 17 avr. 2015 à 14:16, Denis Bitouzé notifications@github.com a écrit :

> > > la 3e doit-elle être similaire à la 2e de couverture : présence du
> > > « logo », contenu dans un cadre sur fond bleu, etc. ?
> > 
> > Je dirais qu'elle doit être identique à la 2 de couverture : cadre sur
> > fond bleu contenant les minis instructions, même police et taille de
> > caractère mais sans le logo.
> 
> Mais avec le bandeau en bas de page comme en 2e de couverture ?

Oui mais qu'en penses Nathalie ?

> > > en absence de publicité, la 4e de couverture doit-elle être
> > > complètement blanche ?
> > 
> > Oui
> 
> Sans bandeau en bas de page donc ?

Oui

> > > En présence de publicité, doit-elle contenir des choses en plus et,
> > > dans l'affirmative, quoi ?
> > 
> > Non rien de plus.
> 
> OK.
> 
> > > Qui se charge des mini instructions aux auteurs ? Que doivent-elles
> > > contenir ?
> > 
> > Boris ou toi me semble t'il. Elles doivent contenir quelques
> > recommandations
> 
> Recommandations LaTeX ?

Oui quelques une genre lien ou trouver la classe plus quelques instructions de type éditorial, mais là c'est vraiment à Boris de décider quels types d'info il souhaite mettre à cet endroit. La seul chose impérative, c'est que cela soit court !

> > et l'adresse url ou trouver les instructions concernant l'utilisation
> > de la classe.
> 
> OK. Il est trop tard pour intégrer la classe à la TeX Live 2014 mais je
> compte la publier bientôt, en tous cas assez tôt (au plus tard le 15
> mai) pour qu'elle soit fournie avec la TeX Live 2015.
> OK
> 
> Il me semble qu'il devrait aussi y avoir des instructions concernant la
> procédure de soumission d'un manuscrit et, pour cela, je vous laisse la
> main.

Oui, c'est ce que je dis plus haut.

> > Si ce n'est pas prêt pour le numéro d'avril, ce n'est pas super grave.
> 
> OK.
> 
> > En revanche il faut prévoir deux pages blanches pour le fichier de
> > couverture généré pour l'imprimeur en l'état actuel des chose.
> 
> OK.

Super.

Claire

**Comment by dbitouze** [comment]
Implémenté.
