### ISSUE TITLE
Numérotation des pages

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#13]
Pourrais tu faire en sorte que la couverture ne soit pas numérotée et que la gazette commence sur une page 1 ?

**Comment by dbitouze** [comment]
Boris confirme-t-il qu'il souhaite cela ?

**Comment by dbitouze** [comment]
Qu'advient-il du bandeau en bas de la 2e de couverture ?

**Comment by clairesmf** [comment]
Il reste tel quel sans numéro de page

**Comment by dbitouze** [comment]
Implémenté.
