### ISSUE TITLE
Publicité

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#15]
Nous allons être amené à devoir insérer des publicités pleine page dans la Gazette (publicité pour des entreprises). L'entreprise X nous fournira un fichier qu'il faudra insérer quelque part en signalant que c'est de la pub. Dans l'ancien format je faisais un \newpage\thispagestyle{Publicité} avant d'inclure mon fichier et sur le format final, à la place du titre courant on avait marqué (Publicité) au dessus de la page de pub. Est ce qu'il serait possible d'avoir quelque chose comme ça ?

**Comment by dbitouze** [comment]
Le titre courant « Publicité » :
- ne doit-il figurer que sur les publicités pour des entreprises, et pas pour celles de la SMF ?
- dans les deux cas, doit-il figurer en 4<sup>e</sup> de couverture ?

**Comment by clairesmf** [comment]
Le 26 avr. 2015 à 09:34, Denis Bitouzé notifications@github.com a écrit :

> Le titre courant « Publicité » :
> 
> ne doit-il figurer que sur les publicités pour des entreprises, et pas pour celles de la SMF ?

Il doit figurer pour toutes les publicités présente dans le fascicule. 

> dans les deux cas, doit-il figurer en 4e de couverture ?

Non, c'est inutile.

**Comment by dbitouze** [comment]
Résolu.
