### ISSUE TITLE
Ordre références dans bibliographie/urgent

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#17]
Un auteur voudrait que les références de sa bibliographie soient dans un orde particulier. Comment puis je faire ? Ensuite toute les références ont toutes le même auteur. Comment ne pas répèter le nom de l'auteur à chaque référence ?

**Comment by dbitouze** [comment]
Il est désormais possible d'ajouter à la commande `\printbibliography` de la classe `gzt` une (ou plusieurs) option(s) de la commande `\printbibliography` originale du package `biblatex`. En
l'occurrence, pour que les références soient classées par ordre de citation dans le texte, il suffit de « surcharger » par `none` la valeur par défaut de la clé `sorting` :

``` latex
\printbibliography[sorting=none]
```
