### ISSUE TITLE
Image sans légende avec copyright

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#19]
Comment insérer une image sans légende avec un copyright ou crédit photo à insérer sur le côté de l'image ?

**Comment by dbitouze** [comment]
Il faudrait préciser où et comment (p.ex. « sur le côté droit, verticalement » ou « sur le côté bas, horizontalement ») ces mentions doivent figurer. À voir avec Boris et/ou Nathalie.

**Comment by clairesmf** [comment]
Boris a tranché : sur le coté droit de l'image, en bas et verticalement et en tout petit.

**Comment by dbitouze** [comment]
Implémenté (qu'il y ait une légende ou pas). Il suffit de passer l'option `copyright`, par exemple :

``` latex
\begin{gztfigure}[title=Petit rhombicuboctaèdre,copyright=Léonard de Vinci]
  \includegraphics[width=\linewidth]{rhombicuboctaedre}
\end{gztfigure}
```
