### ISSUE TITLE
Option 'forauthors'

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#2]
L'option 'forauthors' fait ce qu'il faut quand on l'applique à la classe 'gzt' sur l'ensemble du document. En revanche, il ne se passe rien si on applique cette option à la classe 'gztarticle'. Est-ce normal ?

**Comment by dbitouze** [comment]
Oui, car la classe `gztarticle` est celle qu'utilisent les auteurs et eux n'ont pas besoin des fonctionnalités de l'option `forauthors`. Cette option ne fonctionne certes qu'avec la classe `gls` mais cette dernière peut tout à fait être employée _aussi_ dans les fichiers individuels des auteurs, notamment avec l'option `forauthors`. Pour résumer, une fois qu'un auteur a envoyé un fichier d'article, il suffit d'y remplacer la commande `\documentclass[...]{...}` qu'il a employée par :

``` latex
\documentclass[forauthors]{gzt}
```
