### ISSUE TITLE
Marges intérieures/Dos carré collé

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#20]
Finalement le numéro d'avril aura presque sûrement un dos carré collé. Il faudrait donc prévoir d'agrandir un peu les marges intérieures.

**Comment by dbitouze** [comment]
Je pense ne pas les avoir changées. La marge :
- intérieure est de 15mm ;
- extérieure est de 30mm.

Quelles dimensions dois-je mettre ?

**Comment by clairesmf** [comment]
Oui on avait constaté que les marges intérieures étaient un peu justes avec un dos carré collé pour avoir une lecture confortable en évitant d'avoir à écraser le fascicule pour lire.

**Comment by dbitouze** [comment]
Quelles dimensions doivent-elles avoir ? Peut-être l'imprimeur peut-il nous renseigner à ce sujet...

**Comment by clairesmf** [comment]
Je viens d'avoir Ghislaine. Il faudrait augmenter la marge intérieur de 5 mm et du coup diminuer la marge extérieur de 5 mm. Ce qui reviendrait à décaler un peu le corps du texte sans en changer la largeur.

**Comment by dbitouze** [comment]
Implémenté.

**Comment by dbitouze** [comment]
Réimplémentation qui, à la fois : 
- augmente la marge intérieure ;
- diminue la marge extérieure ;

de 5 mm de façon  automatique si le nombre total de pages (couverture comprise) est 98 pages au moins. Ce seuil convient-il ?

**Comment by clairesmf** [comment]
Pourquoi mettre un seuil ?

**Comment by dbitouze** [comment]
Parce que le décalage de la zone de texte de 5mm vers l'extérieur doit avoir lieu si et seulement si la revue est reliée avec un dos carré-collé, ce qui arrive si et seulement si le nombre total de pages dépasse un certain seuil.

**Comment by clairesmf** [comment]
72 pages alors pour le seuil

**Comment by dbitouze** [comment]
OK, implémenté.
