### ISSUE TITLE
wrapfigure

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#22]
L'environnement wrapfigure n'est pas reconnu par la classe. En fait j'en aurais besoin pour de courtes nécrologies avec une photo de la taille d'une photo d'identité (moitié d'une colonne) autour delaquelle le texte pourrait défiler.

**Comment by clairesmf** [comment]
J'ai résolu mon problème dans l'article avec l'utilisation du package \usepackage{picins} mais chose curieuse autant cela compile très bien avec l'article seul, cela ne compile pas avec le issue.tex. J'ai pourant mis le package au deux endroits.... Si tu peux trouver une solution ca serait bien.

**Comment by dbitouze** [comment]
Il faudrait m'envoyer le fichier et les images pour que je fasse des tests.

**Comment by dbitouze** [comment]
L'erreur vient d'une semi-incompatibilité entre les packages `picins` et `tkz-cd` (que tu as chargés en préambule) : il suffit de charger `picins` avant `tkz-cd` pour que ça marche.
