### ISSUE TITLE
Note de bas de page dans \abstract

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#23]
Le fait de mettre une footnote dans l'environnement \abstract met la note en bas du résumé et non en bas de page... Il faudrait faire en sorte que la note soit situé en bas de page.

**Comment by dbitouze** [comment]
Pour cela, il est nécessaire de recourir à `\footnotemark{}` et `\footnotetext{...}`, cette dernière devant impérativement être saisie (juste) après `\maketitle` :

``` latex
[...]
\begin{abstract}
  Résumé\footnotemark{} contenant une note de bas de page.
\end{abstract}
\maketitle
\footnotetext{Texte de la note de bas de page du résumé.}
[...]
```

**Comment by clairesmf** [comment]
J'ai ulisé cette méthode qui marche bien mais les footnotes générées de cette façon sont sur une seule colonne au lieu de s'étaler sur le bas de page en entier. Du coup elles sont coupées.
Voir : 
\documentclass[forauthors]{gzt}
\usepackage[nowarn]{glossaries}
\makeglossaries
\setacronymstyle{long-sc-short}

\newcommand{\exosept}{\emph{Exo7}}

%
\begin{document}
\title[short={Exo7-- Une interview d'Arnaud Bodin}]{Exo7-- Une interview d'Arnaud Bodin}

\author[
minibio={Antoine Bodin.......}
]{}

\newacronym{moocs}{moocs}{Massive Online Open Courses}
\newacronym{wims}{wims}{Www Interactive Multipurpose Server}

\begin{abstract}

Après avoir publié dans la \gzt un article sur les \gls{moocs}\footnotemark[1] et une analyse récente centrée sur les \gls{wims}\footnotemark[2], nous poursuivons 
notre recension des formations en ligne par un entretien avec Arnaud Bodin, 
qui est à l'initiative du projet \exosept.

\end{abstract}

\maketitle
\footnotetext[1]{\url{http://smf4.emath.fr/Publications/Gazette/2014/140}}
\footnotetext[2]{\url{http://smf4.emath.fr/Publications/Gazette/2015/145}}
\question{Que recouvre le projet \exosept\ ?}
\end{document}

**Comment by clairesmf** [comment]
Deux autres problèmes viennent de surgir que je n'avais pas remarqué : le compteur de footonote ne se remets pas bien. Les notes du texte recommencent à 1. Les footnotetext ne semblent pas être digérées dans le issue.tex

[8 <./mathematics/fleur.jpg>]
<mathematics/PGerard.jpg, id=304, 194.7275pt x 259.97125pt>
<use mathematics/PGerard.jpg>)
Overfull \vbox (6.805pt too high) has occurred while \output is active [9 <./ma
thematics/PGerard.jpg>] (./teaching/Bodin.tex
./teaching/Bodin.tex:39: Undefined control sequence.
\g__gzt_abstract_body_tl ...ve du projet \exosept 
                                                  . \par 
l.39 \footnotetext
                  [1]{\url{http://smf4.emath.fr/Publications/Gazette/2014/140}}

? 
Process aborted

**Comment by clairesmf** [comment]
J'ai réussi à surmonter les difficultés ci-dessus dans l'article qui finalement compile bien en faisant de la sorte (voir ci-dessous).

\documentclass[forauthors]{gzt}
%\documentclass{gztarticle}
\usepackage[nowarn]{glossaries}
\makeglossaries
\setacronymstyle{long-sc-short}

\newcommand{\exosept}{\emph{Exo7}}

%
\begin{document}
\title[short={Exo7-- Une interview d'Arnaud Bodin}]{Exo7-- Une interview d'Arnaud Bodin}

\author[
%affiliation={?},
photo=Kobylanski.jpg,
%email=magdalena.kobylanski@u-pem.fr,
%webpage=http://www.irem.unilim.fr,
minibio={Antoine Bodin.......}
]{}

\newacronym{moocs}{moocs}{Massive Online Open Courses}
\newacronym{wims}{wims}{Www Interactive Multipurpose Server}

\begin{abstract}

Après avoir publié dans la \gzt un article sur les \gls{moocs}\footnotemark[1] et une analyse récente centrée sur les \gls{wims}\footnotemark[2], nous poursuivons 
notre recension des formations en ligne par un entretien avec Arnaud Bodin, 
qui est à l'initiative du projet \exosept.

\end{abstract}

\maketitle*

\footnotetext[1]{\url{http://smf4.emath.fr/Publications/Gazette/2014/140}}
\footnotetext[2]{\url{http://smf4.emath.fr/Publications/Gazette/2015/145}}
\begin{multicols}{2}
\setcounter{footnote}{2}
\question{Que recouvre le projet \exosept\ ?}
\printminibios
%\printbibliography
\end{document}
