### ISSUE TITLE
Problème de césure

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#24]
Il y a de gros problème de césure sur les titres de dossier, comme sur le document ci-joint et je ne peut intervenir manuellement comme sur les titres d'articles ou sur les sections et sous-sections.
![titre-dossier](https://cloud.githubusercontent.com/assets/10724205/7198536/815da054-e4ed-11e4-8b1d-58a589abf103.jpg)

**Comment by dbitouze** [comment]
Devrait être réglé.
