### ISSUE TITLE
Taille des publicités

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#25]
j'aimerais, si c'est possible, qu'elle
occupe la même taille que le corps du texte, c'est à dire que la ligne
du haut du cadre soit aligné avec le haut du texte de la page d'avant
et idem avec la ligne du cadre du bas.

**Comment by dbitouze** [comment]
À la réflexion, je préfère la mise en page actuelle car :
- lorsqu'un cadre délimite un matériel et seulement ce matériel, le
  lecteur comprend de façon subliminale le sens d'un tel cadre : le
  matériel en question est mis en valeur ;
- lorsqu'un cadre délimite toute la zone de texte avec, à l'intérieur,
  un certain matériel, le lecteur peut se demander pourquoi la zone dévolue
  au texte est ici mise en valeur. Cela arriverait en outre de façon
  sporadique : nulle part ailleurs la zone dévolue au texte n'est ainsi
  matérialisée.

ÀMHA, le seul sens que pourrait avoir un cadre comme tu le souhaites est de signaler au lecteur que ce qu'il lit sur cette page n'est pas du texte ordinaire, mais une publicité. Dans ce cas, on pourrait imaginer faire figurer explicitement la mention « Publicité ».

**Comment by clairesmf** [comment]
les lecteurs n'ont pas tous l'esprit tordu….

Faire figurer la mention "Publicité" dans ce cas serait bien. En tout cas elle est indispensable dans le cas ou on a une publicité "extérieure", c'est à dire transmise par un annonceur autre que la SMF et qui fourni un fichier…

**Comment by dbitouze** [comment]
Le 20/04/15 à 12h11, clairesmf notifications@github.com a écrit :

> les lecteurs n'ont pas tous l'esprit tordu….

Il faut penser à ceux qui l'ont et au sens, éventuellement subliminal, d'une maquette.

> Faire figurer la mention "Publicité" dans ce cas serait bien. En tout
> cas elle est indispensable dans le cas ou on a une publicité
> "extérieure", c'est à dire transmise par un annonceur autre que la SMF
> et qui fourni un fichier…

## OK.

Denis
