### ISSUE TITLE
Supression des informations figurant sur la 3 de couverture

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#26]
Comment supprimer et/ou modifier les informations figurant sur la 3 de couverture ? Suffit il de modifier le gzt.cfg en commentant l'environnement des instructions aux auteurs ?

**Comment by dbitouze** [comment]
Non car ça compliquait les choses et, a priori, dès que le comité de rédaction se sera mis d'accord, il y aura presque toujours des instructions aux auteurs. Donc, en attendant, il faut recourir à l'option de classe `noinsidebackcover` (qui ne rend pas vide la 3e : il reste le logo en haut et le bandeau en bas).

Pour avoir une 4e de couverture (entièrement) vide, il faut (et il suffit) qu'il n'y ait pas de fichier `backcover.tex` dans le sous-dossier `backmatter`.
