### ISSUE TITLE
Couleur edito et mot du president

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#27]
Il y a une différence de gris pour l'éditto et le mot du président quand on compile le texte seul ou bien quand on compile l'ensemble du fascicule.

Quand on compile les textes seuls, le gris est clair (trop) et quand on compile le manuscrit les deux articles sortent avec un gris plus foncé. Pourrais tu regarder ça car cela trouble les auteurs ? Je suppose que tu as déjà fait le nécessaire pour foncer ces deux textes par rapport au numéro 143.

**Comment by dbitouze** [comment]
Je ne constate aucune différence.

Depuis le n°143, j'ai passé les gris de CMJN en pourcentage de noir, ce qui devait donner à peu près les mêmes couleurs. Il faudrait que Boris et toi me disiez si c'est assez foncé.

**Comment by clairesmf** [comment]
Boris qui a relu le nouvel dito me dit qu'il a eu du mal à le lire. Il faut donc le foncer encore un peu ainsi que le mot du président.

**Comment by dbitouze** [comment]
Implémenté.

**Comment by clairesmf** [comment]
Ok, merci, mais cela ne compile plus :

Rule 'biber issue': File changes, etc:
   Changed files, or newly in use since previous run(s):

##       'issue.bcf'

## Run number 1 of rule 'biber issue'

---

## Running 'biber  "issue"'

Latexmk: applying rule 'biber issue'...
read_file '/var/folders/qb/c8m79qfj6639r8yf_1bqn2mh0000gn/T/par-736d66/cache-a3cdad92316c60c9c5179d80d6bb51a7a024393c//inc/lib/Biber/LaTeX/recode_data.xml' - sysopen: No such file or directory at /var/folders/qb/c8m79qfj6639r8yf_1bqn2mh0000gn/T/par-736d66/cache-a3cdad92316c60c9c5179d80d6bb51a7a024393c/bda77484.pm line 112.
INFO - This is Biber 1.9
INFO - Logfile is 'issue.blg'
Latexmk: Failed to find one or more biber source files:
  NONE
Collected error summary (may duplicate other messages):
  biber issue: Could not find all biber source files for 'issue'
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
Latexmk: Errors, so I did not complete making targets

Process aborted

Claire

**Comment by clairesmf** [comment]
En fait, en m'y reprenant à plusieurs fois, cela a fini par compiler. Mais il n'y a aucune différence significative entre le gris généré par cette compilation et mon fichier d'avant….
