### ISSUE TITLE
\surname*

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#3]
"\surname\* force les petites capitales tandis que \surname (commande
inutile désormais) ne fait rien. Tu peux continuer à utiliser \surname*
pour les noms de personnes mais ce, donc, seulement pour les noms de
personnes figurant dans les titres d'articles. Si tu veux, pour les
futurs numéros, je peux faire en sorte que ce soit la version non
étoilée qui mette en petites capitales, et supprimer la version étoilée."

Je veux bien, ça me semble plus logique.

**Comment by dbitouze** [comment]
`\surname` applique désormais les petites capitales à son argument. `\surname*` a été supprimé (pense à modifier le fichier `avila.tex` qui l'utilisait).
