### ISSUE TITLE
Probleme Couverture/tranche

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#30]
J'ai beaucoup de mal à compiler. Il faut que je m'y reprenne à plusieurs fois. J'ai généré la couverture après plusieurs essai. La 3 de couv. contient toujours les instructions aux auteurs. Mais chose plus curieuse, la tranche n'est plus blanche au niveau de l'image : il s'est créé un cartouche blanc contenant "Gazette des mathématiciens" ce qui change par rapport au numéro 143 ce qui n'est pas souhaitable. En plus il me semble qu'elle a diminué en taille par rapport à la compilation précédente.

**Comment by dbitouze** [comment]
Résolu.
