### ISSUE TITLE
Probleme pdf Gazette

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#31]
Il y a un problème avec le pdf généré lors de la compilation. Si je l'ouvre avec Acrobat ou Reader et que j'essaye d'imprimer, cela quitte brutalement les logiciels. C'est très génant car du coup je ne peux faire des essais d'impression. Certains utilisateurs du site de la SMF m'ont fait part de leur difficulté à lire le pdf à l'écran depuis leur navigateur : il leur faut télécharger le fichier en local pour pouvoir le lire. Les deux problèmes sont peut être liés....

**Comment by dbitouze** [comment]
Je ne vois pas trop d'où cela peut venir, sauf éventuellement de certains pictogrammes, notamment celui de la rubrique « Raconte-moi » : sur mes machines, la page qui le contient met un temps anormalement long à s'afficher.

Ce serait intéressant de savoir si les utilisateurs du site rencontrent le problème avec tous les articles, ou bien seulement avec certains d'entre eux.

**Comment by clairesmf** [comment]
Les utilisateurs du site rencontrent ce problème avec le pdf de l'ensemble de la Gazette (issue.pdf)

**Comment by dbitouze** [comment]
Peut-être est-ce alors la taille du PDF (14 Mo) qui pose problème à l'afficheur intégré à leur navigateur Web.

**Comment by clairesmf** [comment]
Oui, c'est ce que j'ai répondu, mais ce qui m'inquiète est le problème que j'ai aussi avec l'ouverture du pdf via Acrobat ou reader…
