### ISSUE TITLE
dossier backmatter

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#32]
Quand le dossier backmatter est vide, la quatrième de couverture est blanche ce qui est très bien. En revanche si je mets un fichier backcover.tex dans le dossier et que ce fichier contient soit un \gztinput ou un \includegraphics, cela ne compile pas. j'ai fait le test avec un fichier pdf. Donc pour l'instant imposible de mettre une publicité en page 4 de couverture.

**Comment by dbitouze** [comment]
Résolu.
