### ISSUE TITLE
Rapport moral/dossier frontmatter

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#33]
Le rapport moral doit paraitre dans la Gazette de juillet (c'est habituel). Il faut donc prévoir un endroit pour le mettre. Le rapport moral est en quelque sorte "hors rubrique", ou devrait rendre place dans une rubrique "SMF" comme c'était le cas dans l'ancien format de la Gazette. Ne serait il pas judicieux de nommer le dossier "frontmatter" SMF et d'y inclure le rapport moral sous forme d'un article normal ? C'est assez urgent car je suis en train de le composer et je voudrais le faire directement au format Gazette.

**Comment by dbitouze** [comment]
Où en est-on de cette demande de fonctionnalité ?

**Comment by clairesmf** [comment]
Je me suis débrouillée et comme cela n'arrive qu'une fois par an, il suffira que je note ma bidouille…

Claire

**Comment by dbitouze** [comment]
Implémenté (`\moralreport`).
