### ISSUE TITLE
virgule dans le titre d'un dossier, rubrique dossier

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#34]
J'ai remarqué que la présence d'une virgule dans un titre de dossier de la rubrique "dossier" posait problème et empêchait la compilation. En revanche le "-" passe très bien. On sera sans doute amené un jour à avoir un titre de dossier contenant des virgules, il faudrait donc voir ça.

**Comment by dbitouze** [comment]
Les options de la commande `\dossier` sont spécifiées sous la forme de clé/valeurs séparées par des virgules donc, pour que les virgules contenues dans leurs valeurs ne soient pas considérées comme des séparateurs d'options, il suffit que ces valeurs soient spécifiées entre paires d'accolades ; si une valeur ne contient pas de virgule, la paire d'accolades l'entourant est facultative. Ceci est vrai pour le résumé (`abstract=...` ou `abstract={...}`) comme pour le titre (`title=...` ou `title={...}`) :

``` latex
\dossier[
  abstract={bla bla, bla bla},
  title={bla, bla, bla}
]
```
