### ISSUE TITLE
\mathrm dans \subsection

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#37]
Un truc curieux : \mathrm dans \subsection n'est pas digéré alors que \rm et \text en mode math le sont. Est-ce normal ?

**Comment by dbitouze** [comment]
Un ECM serait le bienvenu.

**Comment by clairesmf** [comment]
Je ne sais pas faire….

Je sais que tu m'as expliqué, mais je n'ai pas bien compris ce que cela signifiait…

**Comment by dbitouze** [comment]
Il suffit de créer un document complet et minimal :
- complet parce qu'il contient au moins :
  - `\documentclass{...}`, dans notre cas, par exemple `\documentclass{gztarticle}` ;
  - l'environnement `document` (c.-à-d. la paire `\begin{document}` et `\end{document}`) ; 
- minimal parce qu'il ne doit contenir que :
  - les packages ;
  - le texte ;
  
  nécessaires à la mise en évidence du problème.

Dans le cas de la présente « issue », ça donnerait donc :

``` latex
\documentclass{gztarticle}
\begin{document}
\section{Test $\mathrm{F}$}
\section{Test ${\rm F}$}
\section{Test $\text{F}$}
\end{document}
```

Je confirme le problème. Il est dû au fait que les titres de sections sont reproduits dans les signets qui ne peuvent pas contenir de symboles mathématiques. Ceux-ci sont donc à éviter dans les titres de sections si possible ; sinon, il faut recourir à la commande `\texorpdfstring{texte/code TeX}{texte/code non TeX}`. Par exemple, ça donnerait ici :

``` latex
\documentclass{gztarticle}
\begin{document}
\section{Test \texorpdfstring{$\mathrm{F}$}{F}}
\section{Test ${\rm F}$}
\section{Test $\text{F}$}
\end{document}
```

**Comment by clairesmf** [comment]
Ok, ça revient à isoler uniquement le problème.

Le 15 juin 2015 à 14:18, Denis Bitouzé notifications@github.com a écrit :

> Il suffit de créer un document complet et minimal :
> 
> complet parce qu'il contient au moins :
> \documentclass{...}, dans notre cas, par exemple \documentclass{gztarticle} ;
> l'environnement document (c.-à-d. la paire \begin{document} et \end{document}) ;
> minimal parce qu'il ne doit contenir que :
> 
> les packages ;
> le texte ;
> nécessaires à la mise en évidence du problème.
> 
> Dans le cas de la présente « issue », ça donnerait donc :
> 
> \documentclass{gztarticle}
> \begin{document}
> \section{Test $\mathrm{F}$}
> \section{Test ${\rm F}$}
> \section{Test $\text{F}$}
> \end{document}
> Je confirme le problème. Il est dû au fait que les titres de sections sont reproduits dans les signets qui ne peuvent pas contenir de symboles mathématiques. Ceux-ci sont donc à éviter dans les titres de sections si possible ; sinon, il faut recourir à la commande \texorpdfstring{texte/code TeX}{texte/code non TeX}. Par exemple, ça donnerait ici :
> 
> \documentclass{gztarticle}
> \begin{document}
> \section{Test \texorpdfstring{$\mathrm{F}$}{F}}
> \section{Test ${\rm F}$}
> \section{Test $\text{F}$}
> \end{document}
> —
> Reply to this email directly or view it on GitHub.

Je comprends pas bien, l'exemple  que tu donnes
\section{Test \texorpdfstring{$\mathrm{F}$}{F}}

ne corresponds pas à

\texorpdfstring{texte/code TeX}{texte/code non TeX} et je ne vois pas bien comment mettre en plus une lettre grecque dans tout ça ainsi que des guillemets.

mon titre de sous-section doit ressembler à \subsection{La \enquot{Conjecture $\mathrm{AA}(\delta)}}

Claire

**Comment by dbitouze** [comment]
> Je comprends pas bien, l'exemple que tu donnes \section{Test \texorpdfstring{$\mathrm{F}$}{F}} ne corresponds pas à \texorpdfstring{texte/code TeX}{texte/code non TeX}

Si : 
- dans le 1er argument peut sans problème figurer presque tout texte et code LaTeX (c'est ce qui sera affiché partout dans le PDF, sauf dans les signets) ;
- dans le 2e argument ne peut pas figurer n'importe quel texte ou code LaTeX (c'est ce qui sera affiché seulement dans les signets).

> je ne vois pas bien comment mettre en plus une lettre grecque dans tout ça ainsi que des guillemets. mon titre de sous-section doit ressembler à \subsection{La \enquot{Conjecture $\mathrm{AA}(\delta)}}

Ceci devrait aller :

``` latex
\section{La \enquote{conjecture \texorpdfstring{$\mathrm{AA}(\delta)$}{AA (delta)}}}
```

Ah, je viens de trouver une solution plus satisfaisante pour la lettre grecque (le problème avec `\mathrm` persiste mais peut être contourné avec `\texorpdfstring`): il suffit d'ajouter en préambule :

``` latex
\hypersetup{pdfencoding=auto,psdextra}
```

comme dans l'exemple suivant :

``` latex
\documentclass{gztarticle}
\hypersetup{pdfencoding=auto,psdextra}
\begin{document}
\section{La \enquote{conjecture \texorpdfstring{$\mathrm{AA}(\delta)$}{AA (\delta)}}}
\end{document}
```

**Comment by dbitouze** [comment]
J'oubliais : le recours à `{\rm ...}` est désormais déconseillé. Il vaut mieux recourir à `\textrm{...}`.

**Comment by clairesmf** [comment]
Oui, c'est pour ça qu'en principe j'ai remplacé tous les \rm du texte de Matheron par \mathrm.

**Comment by dbitouze** [comment]
OK, mais à n'utiliser qu'en mode mathématique.
