### ISSUE TITLE
Subtitle/short

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#38]
Comment faire pour avoir un titre court vide dans un sous-titre de façon à ce que dans la table des matières seul le titre court du titre principal de l'article apparraisse ? Si je mets un faux blanc, cela me créé un tiret dans la TDM et si je ne mets rien, c'est le sous titre qui apparait dans la table des matières à côté du titre court du titre principal.

**Comment by dbitouze** [comment]
Peux-tu fournir un ECM ?

**Comment by clairesmf** [comment]
Difficile car ça compile bien, mais c'est dans la table des matières que ça ne fait pas ce qu'il faut.

**Comment by dbitouze** [comment]
Justement, montre-moi, dans un ECM, ce que tu obtiens (certes sans erreur de compilation) et qui ne correspond pas à ce que tu voudrais obtenir.

**Comment by clairesmf** [comment]
\documentclass[forauthors]{gzt}
%\documentclass{gztarticle}
\usepackage[nowarn]{glossaries}
\makeglossaries
\setacronymstyle{long-sc-short}

\newacronym{wims}{wims}{Www Interactive Multipurpose Server}
\newacronym{moocs}{MOOCs}{Massive Online Open Courses}
\newacronym{ent}{ent}{environnement numériques de travail}
\newacronym{unisciel}{Unisciel}{Université des sciences en ligne}

%
\begin{document}
\title[short={Plates-formes d'apprentissage et \textsc{wims}}]{Plates-formes d'apprentissage et \textsc{wims}}
\subtitle[]{Un voyage dans l'enseignement 3.0}

\end{document}

**Comment by dbitouze** [comment]
Attention, ce n'était pas un ECM. Ce qui l'aurait été est par exemple :
- Contenu de `issue.tex` :

``` latex
\documentclass{gzt}
\issuesetup{number=145}
\begin{document}
\gzttableofcontents
\gztinput{teaching/}{test.tex}
\end{document}
```
- Contenu de `test.tex` :

``` latex
\title[short=Titre court]{Titre long}%
\subtitle[short={}]{Sous-titre long}%
\author{Nom, Prénom}%
\maketitle
```

et ça m'aurait fait gagner du temps...

L'option pour ce genre de situation était déjà configurée, mais son action pas encore programmée. C'est désormais chose faite. Fais donc un `git pull` et recours à l'option `notintoc` de la commande `\subtitle`. Par exemple, avec le même `issue.tex`, le fichier `test.tex` suivant donne le résultat escompté :

``` latex
\title[short=Titre court]{Titre long}%
\subtitle[notintoc]{Sous-titre long}%
\author{Nom, Prénom}%
\maketitle
```

**Comment by clairesmf** [comment]
Désolée mais j'ai encore un peu de mal à déterminer exactement quoi mettre pour un ECM… 
Le 22 juin 2015 à 14:30, Denis Bitouzé notifications@github.com a écrit :

> Attention, ce n'était pas un ECM. Ce qui l'aurait été est par exemple :
> 
> Contenu de issue.tex :
> \documentclass{gzt}
> \issuesetup{number=145}
> \begin{document}
> \gzttableofcontents
> \gztinput{teaching/}{test.tex}
> \end{document}
> Contenu de test.tex :
> \title[short=Titre court]{Titre long}%
> \subtitle[short={}]{Sous-titre long}%
> \author{Nom, Prénom}%
> \maketitle
> et ça m'aurait fait gagner du temps...

Encore désolée…

> L'option pour ce genre de situation était déjà configurée, mais son action pas encore programmée. C'est désormais chose faite. Fais donc un git pull et recours à l'option notintoc de la commande \subtitle. Par exemple, avec le même issue.tex, le fichier test.tex suivant donne le résultat escompté :
> 
> \title[short=Titre court]{Titre long}%
> \subtitle[notintoc]{Sous-titre long}%
> \author{Nom, Prénom}%
> \maketitle
> —
> Reply to this email directly or view it on GitHub.

Ok, merci, je vais tester.
