### ISSUE TITLE
Gestion des acronymes au niveau d'un dossier ou du fascicule entier

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#39]
Je réalise que j'ai défini des acronymes identiques à plusieurs endroits dans des articles différents. Est ce que les acronymes dans ce cas sont gérés au niveau du fascicule ? Si non comment faut il que je fasse pour que cela le soit ?

**Comment by dbitouze** [comment]
> Est ce que les acronymes dans ce cas sont gérés au niveau du fascicule ? Si non comment faut il que je fasse pour que cela le soit ?

De même qu'il ne pourrait y avoir deux nouvelles commandes de même nom créées au moyen de `\newcommand`, il est indispensable qu'il y ait unicité de `⟨clé⟩` parmi tous les acronymes créés au moyen de :

``` latex
\newacronym{⟨clé⟩}{⟨forme courte⟩}{⟨forme longue⟩}
```
