### ISSUE TITLE
Probleme impression pdf

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#41]
un problème que plusieurs personnes m'avaient déjà signalé au moment de la sortie du numéro de janvier :  le pdf généré et mis en accès sur le site de la SMF, quand il s'ouvre dans un navigateur, fait tout planter et refuse de s'imprimer… C'est apparemment le même phénomène. Frédérique Petit en effet ouvre les pdf dans son navigateur : Safari (7.0.6) sous mac OSX (10.9.5)

**Comment by dbitouze** [comment]
Peux-tu me donner un lien vers un des fichiers pour lequel le problème se produit ?

**Comment by clairesmf** [comment]
Tu trouvera un des fichiers posant problème à l'adresse :+1: Legall.pdf   http://smf4.emath.fr/transfert/?1198f585909aeba5080889d7771fcc5a542a9a97
