### ISSUE TITLE
\textsc dans minitoclist

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#42]
Apparemment le \textsc n'est pas accepté dans la minitoclist de la couverture. cela fait tout planter. Il faudrait faire en sorte qu'on puisse mettre du texte en \texts en particulier pour les acronymes.

**Comment by dbitouze** [comment]
Peux-tu fournir un ECM ?

**Comment by clairesmf** [comment]
Voilà, j'espère que ça ira.

**Comment by dbitouze** [comment]
Euh... tu as dû oublier de l'inclure.

**Comment by clairesmf** [comment]
Non non, je viens de vérifier. En fait quand on répond directement aux mails envoyés par github les documents attachés ne passent pas. je l'ai récupéré sur ma machine et le voilà.

Claire

Claire Ropartz
Secrétariat SMF
Tél : 01 44 27 67 96
Fax : 01 40 46 90 96
smf@dma.ens.fr

**Comment by dbitouze** [comment]
> En fait quand on répond directement aux mails envoyés par github les documents attachés ne passent pas. je l'ai récupéré sur ma machine et le voilà.

En effet : la possibilité de répondre par mail est une facilité offerte pour ne pas avoir besoin de le faire sur la page Web de GitHub mais, au final, c'est par ce biais que le message apparaît et il n'y a pas de possibilité d'attacher des fichiers. Le mieux est donc de faire figurer le fichier dans le texte du message.

En l'occurrence, il ne figure toujours pas, comme tu peux le constater ici :

https://github.com/dbitouze/gzt/issues/42#issuecomment-118502848

**Comment by clairesmf** [comment]
Voilà :

```
\documentclass[%
% pagegrid=1mm%
% ,showframe%
% ,forauthors
% ,draft
 output=frontcover,
 %output=insidepages,
 %output=backcover,
]{gzt}
\usepackage[nowarn]{glossaries}
\makeglossaries
\setacronymstyle{long-sc-short}
%
\issuesetup{number=145}                 %mettre le numéro en cours ici.
%
\minitoc{                               %table des matières sur la couverture.     
  \begin{minitoclist}
  \item[L'impact socio-économique des mathématiques]                          %mettre le nom du dossier entre crochets.
  \item*[Diffusion des savoirs] Plates-formes d'apprentissage et \textsc{wims}
    \item*[Parité] Juste un verre, et plus si affinités               %mettre le nom de la rubrique entre crochets et le titre de l'article après les crochets.
\item*[Racontes-moi...] la dimension fractale
  \end{minitoclist}
}
\end{document}
```

**Comment by dbitouze** [comment]
OK. Attention, il manquait le `\begin{document}` qui faisait que ça ne pouvait pas compiler : il faut tester les ECM qu'on envoie.

Toujours est-il que l'ECM suivant compile parfaitement chez moi (avec l'image du n°144 en guise de `frontcover.jpg` dans le dossier `images`) :

``` latex
\documentclass[output=frontcover]{gzt}
\issuesetup{number=145}
%
\minitoc{%
  \begin{minitoclist}
  \item[L'impact socio-économique des mathématiques]
  \item*[Diffusion des savoirs] Plates-formes d'apprentissage et \textsc{wims}
  \item*[Parité] Juste un verre, et plus si affinités
  \item*[Raconte-moi...] la dimension fractale
  \end{minitoclist}
}
\begin{document}
\end{document}
```

**Comment by clairesmf** [comment]
Oups, un copier-coller raté, désolée…

Finalement Boris souhaite un autre titre dans le mini sommaire sans l'acronyme… Donc finalement tout va bien.

**Comment by dbitouze** [comment]
> Finalement Boris souhaite un autre titre dans le mini sommaire sans l'acronyme… Donc finalement tout va bien.

OK mais confirmes-tu que l'ECM que j'ai fourni compile bien ?

**Comment by dbitouze** [comment]
Pour que je puisse savoir si je peux clore cette « issue », peux-tu confirmer/infirmer que l'ECM que j'ai fourni compile ?
