### ISSUE TITLE
Références non citées dans le texte mais numérotées

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#43]
Je voudrais faire apparaitre dans une biblio des références non citées dans le texte mais de façon à ce qu'elles soient numérotées. \nocite{label} fait bien apparaitre les dites références mais sans les numéroter avec [] devant chacune d'entre elles. Comment résoudre ce problème ?

**Comment by dbitouze** [comment]
Pourtant, dans la bibliographie de l'ECM suivant :

``` latex
\documentclass{gzt}
\usepackage{filecontents}
%
\begin{filecontents}{\jobname.bib}
@Book{            sar,
  author        = {Sartre, Jean-Paul},
  title         = {Les mots},
  publisher     = {Gallimard},
  series        = {Folio},
  date          = {1995-12-31},
  location      = {Paris},
  pagetotal     = {210}
}
@book{            tao,
  title         = {Higher Order Fourier Analysis},
  isbn          = {9780821891957},
  date          = {2012},
  pagetotal     = {202},
  publisher     = {American Mathematical Soc.},
  author        = {Tao, Terence},
  reviewer      = {Queffélec, Hervé},
  reviewerinstitution      = {Université Lille 1},
  language      = {english}
}
\end{filecontents}
%
\addbibresource{\jobname.bib}
%
\nocite{sar}
%
\issuesetup{number=145}
%
\begin{document}
\autocite{tao}

\printbibliography
\end{document}
```

la référence introduite au moyen de `\nocite` figure bien précédée de son numéro (« [1] ») :

```
Références
[1] J.-P. Sartre. Les mots. Folio. Paris : Gallimard, 31 déc. 1995. 210 p.
[2] T. Tao. Higher Order Fourier Analysis. Anglais. American Mathematical Soc., 2012. 202 p. isbn : 9780821891957.
```

Il me faudrait donc un ECM mettant en évidence le problème rencontré.

**Comment by clairesmf** [comment]
Ton ECM corresponds à ce que j'ai fait. Par hasard, j'ai eu l'idée de changer le nom du fichier de biblio (BiblioGerard au lieu de Biblio-Gerard) et le problème a été résolu… 
Curieux, non ?

**Comment by clairesmf** [comment]
Nouveau problème : quand on compile le texte dans le issue.tex, les deux références estampillées \nocite (qui sortent bien finalement dans le texte seul), n'apparaissent pas du tout dans la biblio…..

Peux tu m'aider ?

**Comment by dbitouze** [comment]
Il me faudrait l'ensemble pour que je puisse tester.

**Comment by dbitouze** [comment]
Il devrait suffire de faire figurer les commandes `\nocite` dans le corps du fichier esclave, par exemple juste avant `\printbibliography`. Tu confirmes ?

**Comment by clairesmf** [comment]
Je ne comprends pas bien ta réponse. Les \nocite sont bien dans le fichier esclave au bon endroit. Le fichier escalve compile bien mais mais le fichier issue.tex qui ne fait pas ce qu'il faut et c'est pour cela que je t'ai tout envoyé. Si tu regardes le fichier généré par le issue.tex tu verra qu'il manque les références estampillée \nocite…..

**Comment by dbitouze** [comment]
Sauf erreur de ma part, les 2 commandes `\nocite` qu'il y avait dans le fichier `Gerard.tex` que tu m'as envoyé se trouvaient en _préambule_. Je les ai déplacées dans le _corps_ de ce fichier, juste avant `\printbibliography` et, depuis, que ce soit dans le fichier autonome `Gerard.pdf` ou dans le fichier du numéro complet `issue.pdf`, la biblio à la fin de l'article en question contient :

```
[1] M. Audin. Les systèmes hamiltoniens et leur intégrabilité. Cours Spécialisés. Société Mathématique de France; EDP
Sciences, 2001.
[2] P. Gérard et S. Grellier. « Invariant Tori for the cubic Szegö equation ». Invent. Math. 187 (2012), p. 707–754. issn :
0020-9910.
[3] S. Grellier et P. Gérard. « The cubic szego equation and hankel operators ». prépublication, arXiv: 1508.06814 [math.AP]
(2015).
[4] S. Nazarenko. Wave turbulence. Lecture Notes in Physics. Springer, Heidelberg, 2011.
[5] V. V. Peller. Hankel operators and their applications. Springer Monographs in Mathematics. Springer-Verlag, New York,
2003.
```

y compris, donc, les entrées passées en argument de `\nocite`.

**Comment by clairesmf** [comment]
Merci Denis, mais...

pas chez moi…. C'est peut être un problème de cache biber. Je vais essayer de faire les petites manoeuvres depuis le terminal et je te tiens au courant.
