### ISSUE TITLE
Publicités pleine page

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#44]
Quand on insére un publicité pleine page, il faudrait que celle-ci soit centrée verticalement sur la page et non callée en haut de page. Ca serait plus joli.

**Comment by dbitouze** [comment]
Il suffit de recourir à :

``` latex
\begin{minipage}[c][\textheight][c]{\textwidth}%
\centering\includegraphics[max size={\linewidth}{\textheight}]{images/...}%
\end{minipage}%
```

mais je ferai un commande pour cela.

**Comment by dbitouze** [comment]
Implémenté (`\fullpageadvertisement`).
