### ISSUE TITLE
Fichiers pour imprimeur

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#45]
Pour la génération des fichiers pour l'imprimeur, il faudrait que quand chacune des options est activée, cela génère un fichier avec un nom spécifique. Par exemple quand `backcover` est activée ça génère un fichier `backcover.pdf` que je peux transmettre à l'imprimeur sans micmac de nom et déplacement de fichiers, idem pour les autres options.. ça serait très cool mais je ne sais si c'est du domaine du possible.

**Comment by dbitouze** [comment]
C'est possible mais pas vraiment du côté de LaTeX. Le mieux pour cela est de recourir à un `Makefile`.

**Comment by dbitouze** [comment]
`Makefile` fourni.
