### ISSUE TITLE
Image numérotée mais sans légende

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#46]
Un auteur a présenté des figures numérotées mais sans légende. Je ne vois pas bien comment faire sauf à faire title={~} dans les options de gztfigure mais qui donne un résultat pas très beau.

**Comment by dbitouze** [comment]
Ça peut valoir le coup d'inciter l'auteur à en mettre (pour mémoire, les enseignants sanctionnent généralement les étudiants qui ne mettent pas de légendes à leurs illustrations).

Sinon, pour les cas particuliers, on peut ajouter aux options de l'environnement `gztfigure` toutes celles de l'environnement `tcolorbox` (et assimilés) du package éponyme (cf. sa [documentation](http://mirrors.ctan.org/macros/latex/contrib/tcolorbox/tcolorbox.pdf)), donc notamment l'option `notitle` :

``` latex
\begin{gztfigure}[...,notitle]
\includegraphics[width=\linewidth]{...}
\end{gztfigure}
```

**Comment by clairesmf** [comment]
La figure est bien sans légende, mais pas numérotée….

**Comment by dbitouze** [comment]
Implémenté (cf. environnements `gztfigure-`,  `gztfigure*-`, `gzttable-`, `gzttable*-`).

**Comment by clairesmf** [comment]
Merci. je suppose qu'il faut faire un github…

Claire

**Comment by dbitouze** [comment]
Plus précisément, il faut faire un `git pull` :)
