### ISSUE TITLE
Commande non digérée dans \section

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#47]
Il y a une commande définie par l'auteur comme ci-dessous qui n'est pas digérée.... je ne sais que faire.

``` latex
\documentclass[forauthors]{gzt}



\renewcommand{\S}{\mathbb{S}}


\begin{document}
\title[short={Aspect variationnel des surfaces minimales et conjecture de Willmore}]{Aspect variationnel des surfaces minimales et conjecture de Willmore}


\author[
affiliation={???},
photo=hauswirth.jpg,
%email=magdalena.kobylanski@u-pem.fr,
%webpage=http://www.irem.unilim.fr,
minibio={???.}
]{Hauswirth, L.}

\author[
affiliation={???},
photo=mazet.jpg,
%email=magdalena.kobylanski@u-pem.fr,
%webpage=http://www.irem.unilim.fr,
minibio={???.}
]{Mazet, L.}


\maketitle



\section{Les surfaces minimales}


\subsection{Les surfaces minimales de $\S^3$}
\end{document}
```

**Comment by dbitouze** [comment]
Cet exemple était presque parfaitement minimal :) Un vrai ECM, qui aurait mis en évidence le problème rencontré, aurait par exemple été :

``` latex
\documentclass[forauthors]{gzt}
\begin{document}
\section{Les surfaces minimales de $\mathbb{S}^3$}
\end{document}
```

L'erreur rencontrée, pas facilement identifiable il faut reconnaître, vient de ce que les intitulés de (sous-)sections se retrouvent dans les signets du PDF et, à ce titre, n'acceptent pratiquement aucun passage en mode mathématique. On peut s'en tirer en recourant à l'argument optionnel des commandes `\section` et assimilées dont le contenu servira aux signets à la place du titre « normal » :

``` latex
\documentclass[forauthors]{gzt}
\begin{document}
\section[Les surfaces minimales de S cube]{Les surfaces minimales de $\mathbb{S}^3$}
\end{document}
```

Au passage, je déconseille de recourir un peu aveuglément à des `\renewcommand` tels que `\renewcommand{\S}{\mathbb{S}}` car on peut éventuellement écraser une commande pratique, voire indispensable (ici, `\S` produit « § » et, sait-on jamais, peut-être un autre auteur voudra utiliser ce symbole dans un autre article du même numéro).

**Comment by clairesmf** [comment]
Le 7 déc. 2015 à 18:41, Denis Bitouzé notifications@github.com a écrit :

> Cet exemple était presque parfaitement minimal :) Un vrai ECM, qui aurait mis en évidence le problème rencontré, aurait par exemple été :
> 
> \documentclass[forauthors]{gzt}
> \begin{document}
> \section{Les surfaces minimales de $\mathbb{S}^3$}
> \end{document}

Oui, mais je me disais que peut être l'erreur venait d'un mélange de plusieurs choses...

> L'erreur rencontrée, pas facilement identifiable il faut reconnaître, vient de ce que les intitulés de (sous-)sections se retrouvent dans les signets du PDF et, à ce titre, n'acceptent pratiquement aucun passage en mode mathématique. On peut s'en tirer en recourant à l'argument optionnel des commandes \section et assimilées dont le contenu servira aux signets à la place du titre « normal » :
> 
> \documentclass[forauthors]{gzt}
> \begin{document}
> \section[Les surfaces minimales de S cube]{Les surfaces minimales de $\mathbb{S}^3$}
> \end{document}
> OK pour la section.
> 
> Au passage, je déconseille de recourir un peu aveuglément à des \renewcommand tels que \renewcommand{\S}{\mathbb{S}} car on peut éventuellement écraser une commande pratique, voire indispensable (ici, \S produit « § » et, sait-on jamais, peut-être un autre auteur voudra utiliser ce symbole dans un autre article du même numéro).
> 
> Oui je m'en suis aperçu car j'avais des « § » partout dans le texte….
> La solution est elle de remplacer partout $\S$ par $\mathbb{S}$ ?

Je ne rappelle plus mais la liste de commandes intégrées de ce style sont elles répertoriées quelques part ?

**Comment by dbitouze** [comment]
Justement, pour voir si l'erreur vient d'un mélange de plusieurs choses ou pas, il suffit de « minimimaliser » davantage l'exemple.

Un solution serait plutôt de créer une commande, par exemple `\surf` (comme « surface ») :

``` latex
\newcommand{\surf}{\mathbb{S}}
```

et de remplacer les `\S` du texte original par `\surf`.

Si, par « commandes intégrées de ce style », tu entends les commandes qui produisent des symboles, une liste très à jour (et très complète : 14032 symboles !) se trouve dans le package « comprehensive » (taper `texdoc comprehensive` dans un terminal pour ouvrir sa documentation).
