### ISSUE TITLE
Problème avec \enquote et \itemize

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#48]
J'ai un problème de placement du guillemet fermant après une énumération dans `\enquote`. Il se place tout seul en début de la ligne d'après au lieu de se mettre juste après le dernier item.

Voir

``` latex
\documentclass[forauthors]{gzt}
\addbibresource{Biblio-Rolland.bib}
\begin{document}
 \enquote{blabla
  \begin{itemize}
    \item 1
    \item 2
\end{itemize}}
\end{document}
```

**Comment by dbitouze** [comment]
ECM presque parfait :), seul le `\addbibresource{Biblio-Rolland.bib}` est inutile.

Mais, en fait, cette question ne concerne pas la classe `gzt` comme le montre l'ECM suivant (la commande `\enquote` est fournie par le package `csquotes` qui est automatiquement chargé par la classe `gzt`) :

``` latex
\documentclass{article}
\usepackage{csquotes}
\begin{document}
\enquote{blabla
  \begin{itemize}
    \item 1
    \item 2
\end{itemize}}
\end{document}
```

Le mieux serait donc de poser la question sur un forum dédié à (La)TeX en général, par exemple le site de questions et réponses [texnique.fr](http://texnique.fr/osqa/).

**Comment by clairesmf** [comment]
Je progresse ! Pour ce cas je vais revenir aux bons vieux \og et \fg (après avoir regardé une question similaire sur le forum..)
