### ISSUE TITLE
Image avec légende mais non numérotée

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#49]
Bonjour,

J'ai le cas suivant et je voudrais que la figure (le tableau) ne soit pas numéroté. Comment est-ce possible ?
Merci

```
\begin{gztfigure*}[title=Répartition des inscriptions en fonction du niveau d'étude]
%\begin{figure}
\noindent
\renewcommand{\arraystretch}{1.4}%
\hfill%
\begin{tabular}{|p{4cm}||p{9mm}|p{9mm}|p{9mm}|p{9mm}|p{9mm}|p{9mm}|p{9mm}|@{}l@{}}
\cline{2-8}
\multicolumn{1}{l|}{} 
& \centering Lycée & \centering Prépa 
& \centering L & \centering M & \centering D 
& \centering Prof. & \centering Autre & \\
\hline
\begin{tabular}{@{}l}
Inscriptions \vspace{-1.5mm}\\aux exposés
\end{tabular}
&  \centering 4\% &  \centering 38\% 
&  \centering 16\% &  \centering 9\% &  \centering 3\% 
&  \centering 13\% &  \centering 17\% & \\
\hline
\begin{tabular}{@{}l}
Inscriptions \vspace{-1.5mm}\\à la liste de 
diffusion\footnotemark
\end{tabular} 
&  \centering 6\% &  \centering 29\% 
&  \centering 20\% &  \centering 10\% &  \centering 3\% 
&  \centering 15\% &  \centering 17\% & \\
\hline
\multicolumn{8}{@{}l}{
\addtocounter{footnote}{-1}
\footnotesize \footnotemark~%
Le niveau d'étude indiqué est celui communiqué au moment de l'inscription à la liste de diffusion.
}
\end{tabular}%
\hfill\null

\end{gztfigure*}

```

**Comment by dbitouze** [comment]
Ça ne répond pas à la question, mais pourquoi utiliser `gztfigure*` alors que, pour les tableaux, la classe fournit `gzttable*` ?

**Comment by clairesmf** [comment]
Je me suis mal exprimée : la question est de savoir comment faire pour avoir des figures ou des tableaux avec légende mais non numérotés

**Comment by dbitouze** [comment]
>Je me suis mal exprimée : la question est de savoir comment faire pour avoir des figures ou des tableaux avec légende mais non numérotés

Si je comprends bien, ces figures et tableaux non numérotés ne doivent pas être introduits par les mots clés habituels « Figure » et  « Tableau », et ne comporter dans la zone de titre _que_ la légende. Est-ce bien ce qui est demandé ?

**Comment by clairesmf** [comment]
Oui, c'est exactement ça.

Claire

**Comment by dbitouze** [comment]
Implémenté (cf. environnements `gztframe` et `gztframe*`).
