### ISSUE TITLE
\aside et \aside*

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#5]
Serait il possible que les tirets générés par \aside et \aside\* soient un peu plus courts, deux tirets plutôt que trois ? Quel est l'intérêt d'une telle comande alors qu'il est tellement plus rapide de faire à la main des tirets plutôt que de taper une commande, de repérer le texte à mettre entre accolades.... et comment faire pour qu'un tiret ne se retrouvepas tout seul en fin de ligne ?

**Comment by dbitouze** [comment]
Le changement pour deux tirets est effectif. L'intérêt d'une telle commande est que c'est une commande de fond et pas de forme, et qu'elle assure dès lors l'homogénéité (deux tirets partout ou trois tirets partout, mais pas un mélange des deux). Les colonnes sont trop étroites pour forcer l'espace insécable donc il est possible d'un tiret soit isolé (ce qui n'est d'ailleurs pas exigé typographiquement).
