### ISSUE TITLE
\author et biber

### ISSUE THREAD

**Issue by sgouezel** [dbitouze/gzt#51]
J'ai mis pas mal de temps à me rendre compte que, même s'il n'y a pas de bibliographie, il faut absolument exécuter biber, sans quoi les noms d'auteurs ne sont pas affichés correctement. Un avertissement à cet effet dans la doc pourrait être utile !

Un micro-bug relié : si on modifie le nom d'auteur dans le fichier source puis qu'on compile, il n'est pas demandé en fin de compilation de relancer biber. Mais le nom d'auteur ne sera pas modifié dans le pdf tant qu'on n'aura pas relancé biber...

**Comment by sgouezel** [comment]
Ah, et un ECM, car il en faut toujours un : si on compile l'extrait suivant juste avec pdflatex, l'auteur ne s'affiche jamais (mais la compilation demande d'exécuter biber, donc si on sait lire on peut s'en sortir :). 

\documentclass{gztarticle}
\begin{document}

\title{Mon titre}
\author{Moi}

\maketitle

coucou

\end{document}

**Comment by dbitouze** [comment]
En effet, il serait préférable que cela soit signalé. Je m'en occupe aussitôt que possible.

**Comment by dbitouze** [comment]
La nécessité de lancer une compilation `biber` figure désormais en avertissement dans la documentation.
