### ISSUE TITLE
Fichier gzt.cfg manquant sur CTAN

### ISSUE THREAD

**Issue by sgouezel** [dbitouze/gzt#53]
Un auteur qui souhaite utiliser directement la classe gztarticle fournie par le package gzt sur CTAN me fait remonter le commentaire suivant : à la compilation, il reçoit le message :

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
./Bahouri_Gazettefevrier.tex:23: LaTeX error: "kernel/file-not-found"
! 
! File 'gzt.cfg' not found.
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................

**Comment by dbitouze** [comment]
C'est effectivement un bug que je vais corriger pour la prochaine version.

En attendant, il devrait suffire de créer un fichier `gzt.cfg' vide dans le dossier courant.
