### ISSUE TITLE
Probleme avec derniere version expl3

### ISSUE THREAD

**Issue by sgouezel** [dbitouze/gzt#55]
Depuis la dernière mise à jour de expl3, j'ai l'erreur suivante :

! Undefined control sequence.
<argument> \g__gzt_for_printer_bool 
                                    
l.341 \bool_if:NTF {\g__gzt_for_printer_bool}

Je suppose que l'explication est celle donnée en https://tex.stackexchange.com/questions/383071/what-does-greedy-bool-ifntf-mean  à la fin de la réponse de egreg.

**Comment by dbitouze** [comment]
> Depuis la dernière mise à jour de expl3, j'ai l'erreur suivante :
>
> ! Undefined control sequence.
> <argument> \g__gzt_for_printer_bool 
>                                     
> l.341 \bool_if:NTF {\g__gzt_for_printer_bool}

Oui, désolé de n'avoir pas encore mis à jour.

> Je suppose que l'explication est celle donnée en https://tex.stackexchange.com/questions/383071/what-does-greedy-bool-ifntf-mean à la fin de la réponse de egreg.

Tout à fait : le booléen `\g__gzt_for_printer_bool` est défini dans la classe `gzt.cls` utilisée par les éditeurs du NWEJM pour construire un numéro entier, mais pas dans la classe `gztarticle.cls` utilisée par les auteurs. Jusqu'ici, il n'y avait pas de problème pour ce test conditionnel puisque la branche « Faux » était choisie en l'absence de définition du booléen. Ce n'est plus le cas et, à titre de solution provisoire, il devrait suffire de définir ce dernier (par exemple en préambule) :
```
\ExplSyntaxOn
\bool_new:N \g__gzt_for_printer_bool
\ExplSyntaxOff
```
Je vais publier une version corrigée de la classe dans les prochains jours.

**Comment by sgouezel** [comment]
Ping? J'ai un auteur qui voudrait utiliser la classe gzt du CTAN, mais à qui ça pose problème (le manque de fichier gzt.cfg, cf. issue 53, pourrait éventuellement être résolu par la même occasion). Je proposerais bien une pull request, mais avec les histoires de propagation des fichiers compilés j'ai peur de faire des bêtises.

Sébastien

**Comment by dbitouze** [comment]
Désolé, je n'ai vraiment pas eu le temps de me pencher sur la question et ça risque de durer ainsi encore au moins deux semaines.

Les _pull requests_ sont toujours les bienvenues, même si je ne suis pas certain d'avoir le temps de publier immédiatement une nouvelle version de la classe sur le CTAN.

La solution provisoire que j'ai indiquée plus haut ne fonctionne pas mais, sauf erreur, les lignes :
```
\RequirePackage{expl3}
\ExplSyntaxOn
\bool_new:N \g__gzt_for_printer_bool
\ExplSyntaxOff
```
insérées **avant `\documentclass{gztarticle}`** règlent temporairement le problème.

**Comment by dbitouze** [comment]
Problème réglé dans le dépôt (commit 36783355bd66e5db6c9ee5d1084619de30efe05d).
