### ISSUE TITLE
\gls*{} et \gls{}

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#6]
Je te cite : "La forme non étoilée fait que l'acronyme est un hyperlien vers la liste
des acronymes si elle existe. Comme il n'y a pas de telle liste dans la
Gazette, il est préférable de ne pas mettre d'hyperlien (pour éviter des
warnings inutiles)."
Donc si je comprends bien il ne faut pas utiliser la version non étoilée. Est-ce qu'il serait possible de faire comme pour \surname c'est à dire d'inverser les fonctions entre la version étoilée et non étoilée. Ca serait plus facile et rapide pour la saisie.

**Comment by dbitouze** [comment]
J'ai trouvé une meilleure solution : ni `\gls` ni `\gls*` ne créent d'hyperlien.
