### ISSUE TITLE
Draft

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#7]
J'ai fait tourner la nouvelle classe gztarticle.cls. Il y a la mention "Draft" qui apparait sur le pdf ce qui est très bien. Mais ce filigranne pourait-il être un tout petit peu plus clair car il risque de rendre la relecture des épreuves un peu difficile et pourrait il être accompagné de la date ? Cela permettrait en cas de plusieurs jeu d'épreuves de s'y retrouver. Autre question : comment faire pour le désactiver si nécessaire ?

**Comment by dbitouze** [comment]
Finalement, je retire pour l'instant la mention « Draft ». J'implémenterai plus tard (ce n'est pas urgent), et éventuellement, la possibilité de l'avoir (et alors le couleur sera plus claire). En revanche, je ne vois pas où positionner la date : en filigrane, ce serait peu lisible.

**Comment by dbitouze** [comment]
Oui, car la classe `gztarticle` est celle qu'utilisent les auteurs et eux n'ont pas besoin des fonctionnalités de l'option `forauthors`. Cette option ne fonctionne certes qu'avec la classe `gzt` mais cette dernière peut tout à fait être employée _aussi_ dans les fichiers individuels des auteurs, notamment avec l'option `forauthors`. Pour résumer, une fois qu'un auteur a envoyé un fichier d'article, il suffit d'y remplacer la commande `\documentclass[...]{...}` qu'il a employée par :

``` latex
\documentclass[forauthors]{gzt}
```
