### ISSUE TITLE
\url

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#8]
Est il possible de mettre une adresse \url dans l'affiliation du \author. Que faire quand l'auteur a une adresse ou plusieurs adresses correspondants à des pages perso ?

**Comment by dbitouze** [comment]
> Est il possible de mettre une adresse \url dans l'affiliation du \author.

A priori, rien ne s'y oppose, mais ce serait plus cohérent de recourir à l'option `webpage` faite pour cela.

> Que faire quand l'auteur a une adresse ou plusieurs adresses correspondants à des pages perso ?

L'option `webpage` est prévue pour une seule URL. On peut envisager la possibilité d'en spécifier plusieurs (mais ÀMHA, une seule suffit). Si _vraiment_ c'est nécessaire, ouvrier une autre issue pour demander cette fonctionnalité.
