### ISSUE TITLE
Nom des rubriques

### ISSUE THREAD

**Issue by clairesmf** [dbitouze/gzt#9]
Boris souhaiterait changer le nom de la rubrique "Enseignement" en "Diffusion des savoirs"... Y a t'il un moyen simple de changer le nom des rubriques ?

**Comment by dbitouze** [comment]
Chaque élément :
- résumé ;
- titre ;
- pictogramme ;

d'une rubrique déjà définie (`\dossier`, `\teaching`, `\mathematics`, etc.), peut être redéfini en argument optionnel au moyen des clés suivantes :
- `abstract` ;
- `title` ;
- `pictogram`.

Donc, pour changer le nom de la rubrique « Enseignement » en « Diffusion des savoirs », il suffit désormais (après un `git pull`) de saisir :

``` latex
\teaching[title=Diffusion des savoirs]
```

**Comment by clairesmf** [comment]
Ok, mais ou faut il saisir \teaching[title=Diffusion des savoirs] ? Dans l'article, dans le issue.tex ?

**Comment by dbitouze** [comment]
Plutôt dans `issue.tex`. En tous cas, là où est habituellement utilisée la (seule occurrence de la) commande `\teaching`.

**Comment by clairesmf** [comment]
Cela a très bien marché, mais ce titre est définitif, alors il faudrait peut être faire en sorte que cela soit dans la classe directement.

**Comment by dbitouze** [comment]
Le nom de la rubrique « Enseignement » a été changé en « Diffusion des savoirs » dans la dernière version de la classe.
